import { Flight, Seat } from './types';

// Image paths generated by the system
export const IMAGES = {
  hero: '/src/assets/images/hero_plane_flight_1782837395527.jpg',
  atr42: '/src/assets/images/atr42_regional_1782837409116.jpg',
  vipJet: '/src/assets/images/vip_private_jet_1782837424812.jpg',
  vipInterior: '/src/assets/images/private_jet_interior_1782837441727.jpg',
  charter: '/src/assets/images/regenerated_image_1790344564397.png',
};

export const FLIGHTS_COTO_PARA: Flight[] = [
  {
    id: 'coto-para-1',
    flightNumber: 'AMZ-101',
    departure: 'Cotonou',
    departureCode: 'COO',
    destination: 'Parakou',
    destinationCode: 'PKO',
    departureTime: '07:15',
    arrivalTime: '08:30',
    duration: '1h 15m',
    priceEconomy: 65000,
    priceBusiness: 120000,
    priceVIP: 250000,
    days: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
  },
  {
    id: 'coto-para-2',
    flightNumber: 'AMZ-103',
    departure: 'Cotonou',
    departureCode: 'COO',
    destination: 'Parakou',
    destinationCode: 'PKO',
    departureTime: '11:45',
    arrivalTime: '13:00',
    duration: '1h 15m',
    priceEconomy: 65000,
    priceBusiness: 120000,
    priceVIP: 250000,
    days: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
  },
  {
    id: 'coto-para-3',
    flightNumber: 'AMZ-105',
    departure: 'Cotonou',
    departureCode: 'COO',
    destination: 'Parakou',
    destinationCode: 'PKO',
    departureTime: '16:30',
    arrivalTime: '17:45',
    duration: '1h 15m',
    priceEconomy: 70000,
    priceBusiness: 130000,
    priceVIP: 270000,
    days: ['MON', 'WED', 'FRI', 'SUN'],
  },
];

export const FLIGHTS_PARA_COTO: Flight[] = [
  {
    id: 'para-coto-1',
    flightNumber: 'AMZ-102',
    departure: 'Parakou',
    departureCode: 'PKO',
    destination: 'Cotonou',
    destinationCode: 'COO',
    departureTime: '09:30',
    arrivalTime: '10:45',
    duration: '1h 15m',
    priceEconomy: 65000,
    priceBusiness: 120000,
    priceVIP: 250000,
    days: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
  },
  {
    id: 'para-coto-2',
    flightNumber: 'AMZ-104',
    departure: 'Parakou',
    departureCode: 'PKO',
    destination: 'Cotonou',
    destinationCode: 'COO',
    departureTime: '14:00',
    arrivalTime: '15:15',
    duration: '1h 15m',
    priceEconomy: 65000,
    priceBusiness: 120000,
    priceVIP: 250000,
    days: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
  },
  {
    id: 'para-coto-3',
    flightNumber: 'AMZ-106',
    departure: 'Parakou',
    departureCode: 'PKO',
    destination: 'Cotonou',
    destinationCode: 'COO',
    departureTime: '18:30',
    arrivalTime: '19:45',
    duration: '1h 15m',
    priceEconomy: 70000,
    priceBusiness: 130000,
    priceVIP: 270000,
    days: ['MON', 'WED', 'FRI', 'SUN'],
  },
];

export const FLEET = [
  {
    name: 'ATR 42-500',
    category: 'Vol Régional Régulier',
    capacity: '48 Passagers',
    speed: '550 km/h',
    description: 'Parfait pour relier Cotonou et Parakou avec une efficience inégalée et une sécurité certifiée.',
    image: IMAGES.atr42,
    features: ['Cabine pressurisée', 'Bagages inclus', 'Service à bord', 'Émissions réduites de CO2'],
  },
  {
    name: 'Falcon 2000S VIP',
    category: 'Jet Privé Luxe',
    capacity: '10 Passagers',
    speed: '850 km/h',
    description: 'Le summum du confort pour vos déplacements d\'affaires ou vos urgences gouvernementales.',
    image: IMAGES.vipJet,
    features: ['Intérieur cuir', 'Hôtesse dédiée', 'Champagne à bord', 'Wi-Fi haut débit'],
  },
  {
    name: 'Charter Privé Amazone',
    category: 'Vols Sur Mesure',
    capacity: 'À la demande',
    speed: 'Sur mesure',
    description: 'Une flexibilité totale pour les groupes, délégations officielles ou transports spéciaux.',
    image: IMAGES.charter,
    features: ['Horaires flexibles', 'Terminal privé', 'Discrétion absolue', 'Accompagnement VIP'],
  },
];

export const DESTINATIONS = [
  {
    name: 'Cotonou ↔ Parakou',
    status: 'active',
    description: 'Notre liaison phare. 3 vols quotidiens opérés en toute sécurité pour éviter 8 heures de route éreintantes.',
    code: 'COO ↔ PKO',
    time: '1h 15m',
    image: 'https://images.unsplash.com/photo-1544016768-982d1554f0b9?auto=format&fit=crop&q=80&w=600',
  },
  {
    name: 'Cotonou ↔ Lagos',
    status: 'bientôt',
    description: 'La liaison économique majeure vers le géant nigérian. Évitez les frontières terrestres fastidieuses.',
    code: 'COO ↔ LOS',
    time: '45m',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc1f4767?auto=format&fit=crop&q=80&w=600',
  },
  {
    name: 'Cotonou ↔ Dakar',
    status: 'bientôt',
    description: 'Connectez le Bénin au Sénégal en vol direct premium avec services VIP exclusifs.',
    code: 'COO ↔ DKR',
    time: '3h 30m',
    image: 'https://images.unsplash.com/photo-1509840144519-8d8e5f29d28c?auto=format&fit=crop&q=80&w=600',
  },
  {
    name: 'Cotonou ↔ Abidjan',
    status: 'bientôt',
    description: 'Liaison directe avec la perle des lagunes pour vos opportunités commerciales régionales.',
    code: 'COO ↔ ABJ',
    time: '1h 40m',
    image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=600',
  },
];

export const ADVANTAGES = [
  {
    id: 'adv-1',
    title: '1h15 seulement',
    description: 'Évitez 8 à 10 heures de route dangereuse. Reliez le Nord et le Sud du Bénin en un clin d\'œil.',
    icon: 'Zap',
  },
  {
    id: 'adv-2',
    title: 'Sécurité certifiée',
    description: 'Normes aéronautiques internationales rigoureuses. Pilotes expérimentés et maintenance certifiée.',
    icon: 'ShieldCheck',
  },
  {
    id: 'adv-3',
    title: 'Confort premium',
    description: 'Cabines spacieuses, rafraîchissements locaux et service chaleureux par nos hôtesses béninoises.',
    icon: 'Sparkles',
  },
  {
    id: 'adv-4',
    title: 'Vol rapide et fiable',
    description: 'Taux de ponctualité de 98.7% sur l\'année. Votre temps est précieux, nous le respectons.',
    icon: 'Clock',
  },
];

export const generateSeats = (flightClass: 'economy' | 'business' | 'vip'): Seat[] => {
  const seats: Seat[] = [];
  const rows = flightClass === 'vip' ? 4 : flightClass === 'business' ? 6 : 10;
  
  for (let r = 1; r <= rows; r++) {
    const letters: ('A' | 'B' | 'C' | 'D')[] = ['A', 'B', 'C', 'D'];
    letters.forEach((l) => {
      // randomly book some seats for realism
      const isBooked = Math.random() < 0.35;
      const basePrice = flightClass === 'vip' ? 250000 : flightClass === 'business' ? 120000 : 65000;
      seats.push({
        id: `${r}${l}`,
        row: r,
        letter: l,
        class: flightClass,
        isBooked,
        price: basePrice + (r <= 2 ? 5000 : 0), // Row 1-2 extra spacing premium
      });
    });
  }
  return seats;
};
